### ISSUE TITLE
some questions about trainning

### ISSUE THREAD

**Issue by hustgetlijun** [jinlong17/DA-Detection-Diff-Weather#1]
hello，I want to ask the final model without C5 in the resnet50? and I get the mAP50=38.5%? Can you give  more detail information about trainning?

**Comment by XJWang628** [comment]
> hello，I want to ask the final model without C5 in the resnet50? and I get the mAP50=38.5%? Can you give more detail information about trainning?

Hello, could you please provide the information of the environment configured to run DA-Detect, such as GPU, torch version, cuda version, gcc version, etc. I have tried many times but failed to run it successfully on 2080ti.

**Comment by hustgetlijun** [comment]
/
![image](https://github.com/jinlong17/DA-Detect/assets/59046069/09d6d676-ac9f-4cbd-82b7-c456fa1f1ee8)
![image](https://github.com/jinlong17/DA-Detect/assets/59046069/060c7341-578d-4cdc-85f4-3cfad51f9ca2)
![image](https://github.com/jinlong17/DA-Detect/assets/59046069/4688c56e-0c2b-4044-b474-63394fd23f1d)

**Comment by hustgetlijun** [comment]
the GPU is GV100, cuda version is cuda10.0, torch version is 1.7.1, gcc version is 6.2.0. When run it , you should "python setup.py build develop" and change the config file.

**Comment by hustgetlijun** [comment]
/



> > the GPU is GV100, cuda version is cuda10.0, torch version is 1.7.1, gcc version is 6.2.0. When run it , you should "python setup.py build develop" and change the config file.

**Comment by XJWang628** [comment]
> /
> 
> > > the GPU is GV100, cuda version is cuda10.0, torch version is 1.7.1, gcc version is 6.2.0. When run it , you should "python setup.py build develop" and change the config file.

Thank you for your reply. After installing cuda10.0, I successfully compiled maskrcnn benchmark, but encountered "KeyError: 'Non-existent config key: MODEL.OUTPUT_DIR'" during the process of running train_net.py. I don't know how to solve this, can you help me?
![image](https://github.com/jinlong17/DA-Detect/assets/74861454/dda7bfff-2e71-47e3-8fc7-fa7ea615bf9a)

**Comment by hustgetlijun** [comment]
I use the code of “python3 tools/train_net_triplet.py --config-file "configs/da_faster_rcnn/e2e_triplet_da_faster_rcnn_R_50_C4_cityscapes_to_foggy_cityscapes.yaml"”, and in the config-file as shown belew:







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月24日(星期三) 晚上7:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jinlong17/DA-Detect] some questions about trainning (Issue #1)





  
/
   
the GPU is GV100, cuda version is cuda10.0, torch version is 1.7.1, gcc version is 6.2.0. When run it , you should "python setup.py build develop" and change the config file.
    
Thank you for your reply. After installing cuda10.0, I successfully compiled maskrcnn benchmark, but encountered "KeyError: 'Non-existent config key: MODEL.OUTPUT_DIR'" during the process of running train_net.py. I don't know how to solve this, can you help me?

**Comment by XJWang628** [comment]
> I use the code of “python3 tools/train_net_triplet.py --config-file "configs/da_faster_rcnn/e2e_triplet_da_faster_rcnn_R_50_C4_cityscapes_to_foggy_cityscapes.yaml"”, and in the config-file as shown belew:
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年5月24日(星期三) 晚上7:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [jinlong17/DA-Detect] some questions about trainning (Issue #1) / the GPU is GV100, cuda version is cuda10.0, torch version is 1.7.1, gcc version is 6.2.0. When run it , you should "python setup.py build develop" and change the config file. Thank you for your reply. After installing cuda10.0, I successfully compiled maskrcnn benchmark, but encountered "KeyError: 'Non-existent config key: MODEL.OUTPUT_DIR'" during the process of running train_net.py. I don't know how to solve this, can you help me? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

I really appreciate your reply, it's really helpful to me. Would you mind leaving a contact information (e.g. an email address) so I can ask some questions separately?

**Comment by hustgetlijun** [comment]
You can add the QQ: 1694587481



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月24日(星期三) 晚上7:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jinlong17/DA-Detect] some questions about trainning (Issue #1)





  
I use the code of “python3 tools/train_net_triplet.py --config-file "configs/da_faster_rcnn/e2e_triplet_da_faster_rcnn_R_50_C4_cityscapes_to_foggy_cityscapes.yaml"”, and in the config-file as shown belew:
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年5月24日(星期三) 晚上7:16 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [jinlong17/DA-Detect] some questions about trainning (Issue #1) / the GPU is GV100, cuda version is cuda10.0, torch version is 1.7.1, gcc version is 6.2.0. When run it , you should "python setup.py build develop" and change the config file. Thank you for your reply. After installing cuda10.0, I successfully compiled maskrcnn benchmark, but encountered "KeyError: 'Non-existent config key: MODEL.OUTPUT_DIR'" during the process of running train_net.py. I don't know how to solve this, can you help me? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
I really appreciate your reply, it's really helpful to me. Would you mind leaving a contact information (e.g. an email address) so I can ask some questions separately?

**Comment by olivia001128** [comment]
Hello,I meet an import errror,as follows:  
File "tools/train_net.py", line 19, in <module>
    from maskrcnn_benchmark.engine.trainer import do_train, do_da_train
ImportError: cannot import name 'do_da_train' from 'maskrcnn_benchmark.engine.trainer'
i have checked the function is exists in the py document and the import path is right,so i donnot know where is wrong ,could someone  give me some guidence! thanks

**Comment by olivia001128** [comment]
> I use the code of “python3 tools/train_net_triplet.py --config-file "configs/da_faster_rcnn/e2e_triplet_da_faster_rcnn_R_50_C4_cityscapes_to_foggy_cityscapes.yaml"”, and in the config-file as shown belew:
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年5月24日(星期三) 晚上7:16 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [jinlong17/DA-Detect] some questions about trainning (Issue #1) / the GPU is GV100, cuda version is cuda10.0, torch version is 1.7.1, gcc version is 6.2.0. When run it , you should "python setup.py build develop" and change the config file. Thank you for your reply. After installing cuda10.0, I successfully compiled maskrcnn benchmark, but encountered "KeyError: 'Non-existent config key: MODEL.OUTPUT_DIR'" during the process of running train_net.py. I don't know how to solve this, can you help me? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

i met the same problem ,so have you solved it ? Looking forward to your relpy,thanks a lot!

**Comment by jinlong17** [comment]
> > hello，I want to ask the final model without C5 in the resnet50? and I get the mAP50=38.5%? Can you give more detail information about trainning?
> 
> Hello, could you please provide the information of the environment configured to run DA-Detect, such as GPU, torch version, cuda version, gcc version, etc. I have tried many times but failed to run it successfully on 2080ti.



> > hello，I want to ask the final model without C5 in the resnet50? and I get the mAP50=38.5%? Can you give more detail information about trainning?
> 
> Hello, could you please provide the information of the environment configured to run DA-Detect, such as GPU, torch version, cuda version, gcc version, etc. I have tried many times but failed to run it successfully on 2080ti.

Hi, you can search the how to install maskrcnn_benchmask in the CSDN or something, because the whole codes are based on the maskrcnn_benchmask, which is the old version.

**Comment by kokturkozge** [comment]
> Hello,I meet an import errror,as follows: File "tools/train_net.py", line 19, in from maskrcnn_benchmark.engine.trainer import do_train, do_da_train ImportError: cannot import name 'do_da_train' from 'maskrcnn_benchmark.engine.trainer' i have checked the function is exists in the py document and the import path is right,so i donnot know where is wrong ,could someone give me some guidence! thanks

Hello! Anyone faced or solved this issue? I'm also receiving the same error while running train_net_triplet.py. Thanks

**Here is the error message:**

Traceback (most recent call last):
  File "D:\detectron2\DA-Detect\tools\train_net_triplet.py", line 23, in <module>
    from maskrcnn_benchmark.data import make_data_loader, make_data_loader_da
  File "D:\detectron2\DA-Detect\tools\cityscapes\maskrcnn_benchmark\data\__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "D:\detectron2\DA-Detect\tools\cityscapes\maskrcnn_benchmark\data\build.py", line 11, in <module>
    from . import datasets as D
  File "D:\detectron2\DA-Detect\tools\cityscapes\maskrcnn_benchmark\data\datasets\__init__.py", line 3, in <module>
    from .coco import COCODataset
  File "D:\detectron2\DA-Detect\tools\cityscapes\maskrcnn_benchmark\data\datasets\coco.py", line 3, in <module>
    import torchvision
  File "C:\Users\koktu\miniconda3\envs\detectron2\lib\site-packages\torchvision\__init__.py", line 7, in <module>
    from torchvision import datasets
  File "C:\Users\koktu\miniconda3\envs\detectron2\lib\site-packages\torchvision\datasets\__init__.py", line 1, in <module>
    from .lsun import LSUN, LSUNClass
  File "C:\Users\koktu\miniconda3\envs\detectron2\lib\site-packages\torchvision\datasets\lsun.py", line 2, in <module>
    from PIL import Image
  File "C:\Users\koktu\miniconda3\envs\detectron2\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1

**And my environment info:** 

(detectron2) D:\detectron2>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

(detectron2) D:\detectron2>pip list
Package                 Version            Editable project location
----------------------- ------------------ -------------------------
absl-py                 2.1.0
antlr4-python3-runtime  4.9.3
appdirs                 1.4.4
backcall                0.2.0
black                   23.3.0
brotlipy                0.7.0
cachetools              5.3.2
certifi                 2022.12.7
cffi                    1.15.1
charset-normalizer      3.3.2
cityscapesScripts       2.2.2
click                   8.1.7
cloudpickle             2.2.1
colorama                0.4.6
coloredlogs             15.0.1
cryptography            39.0.1
cycler                  0.11.0
Cython                  3.0.8
decorator               5.1.1
detectron2              0.6                d:\detectron2
filelock                3.9.0
flit_core               3.6.0
fonttools               4.38.0
fvcore                  0.1.5.post20221221
google-auth             2.28.0
google-auth-oauthlib    0.4.6
grpcio                  1.60.1
h5py                    3.8.0
huggingface-hub         0.10.1
humanfriendly           10.0
hydra-core              1.3.2
idna                    3.6
imageio                 2.31.2
importlib-metadata      6.7.0
importlib-resources     5.12.0
iopath                  0.1.9
ipython                 7.31.1
jedi                    0.18.1
kiwisolver              1.4.5
Markdown                3.4.4
MarkupSafe              2.1.5
matplotlib              3.5.3
matplotlib-inline       0.1.6
mkl-fft                 1.3.1
mkl-random              1.2.2
mkl-service             2.4.0
msvc-runtime            14.29.30133
mypy-extensions         1.0.0
networkx                2.6.3
numpy                   1.21.5
oauthlib                3.2.2
omegaconf               2.3.0
opencv-python           4.9.0.80
packaging               23.2
parso                   0.8.3
pathspec                0.11.2
pickleshare             0.7.5
Pillow                  9.3.0
pip                     22.3.1
platformdirs            4.0.0
portalocker             2.7.0
prompt-toolkit          3.0.36
protobuf                3.20.3
pyasn1                  0.5.1
pyasn1-modules          0.3.0
pycocotools             2.0.7
pycparser               2.21
Pygments                2.11.2
pyOpenSSL               23.0.0
pyparsing               3.1.1
pyquaternion            0.9.9
pyreadline              2.1
PySocks                 1.7.1
python-dateutil         2.8.2
PyWavelets              1.3.0
pywin32                 306
PyYAML                  6.0.1
requests                2.31.0
requests-oauthlib       1.3.1
rsa                     4.9
scikit-image            0.19.3
scipy                   1.7.3
setuptools              65.6.3
six                     1.16.0
tabulate                0.9.0
tensorboard             2.11.2
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
termcolor               2.3.0
tifffile                2021.11.2
timm                    0.6.13
tomli                   2.0.1
torch                   1.7.1
torchaudio              0.7.2
torchvision             0.8.2
tqdm                    4.66.2
traitlets               5.7.1
typed-ast               1.5.5
typing                  3.7.4.3
typing_extensions       4.7.1
urllib3                 2.0.7
wcwidth                 0.2.5
Werkzeug                2.2.3
wheel                   0.38.4
win-inet-pton           1.1.0
wincertstore            0.2
yacs                    0.1.8
zipp                    3.15.0
