### ISSUE TITLE
About rainy mask data

### ISSUE THREAD

**Issue by qiuqc1** [jinlong17/DA-Detection-Diff-Weather#2]
When generating the rainy city landscape data set, what exactly is the rainy mask? I changed the absolute path to /DA-Detect/data/Streaks_Garg06, but I did not get the generated auxiliary domain.
I see that the rain_mask_path in the open source code is /home/jinlong/Desktop/rainy_mask/final_heavy, but what is this final_heavy?
After I run generate_rainy_cityscape.py, the results produced are all 0
![image](https://github.com/jinlong17/DA-Detect/assets/105922275/d187d489-e701-4742-a87d-379745d7fa5b)
![image](https://github.com/jinlong17/DA-Detect/assets/105922275/08d5ab16-931f-49f8-8d90-cc7d90702b5e)
![image](https://github.com/jinlong17/DA-Detect/assets/105922275/0a50bcbc-ce46-46b4-8957-bfe2673adb95)

**Comment by jinlong17** [comment]
Hello, the rainy mask data is the data in the Streaks_Garg06 folder. Your error may be a problem with reading the cityscapes data set. It may not read any pictures. It is mainly a problem with your path settings. You can try to debug your code.
