### ISSUE TITLE
about the multiDoamin labels? (关于不同域的标签问题)

### ISSUE THREAD

**Issue by farzeber** [jinlong17/DA-Detection-Diff-Weather#3]
我看代码中，不同域的labels为什么也有关于物体的boxes信息，按照我的理解 targetDomain中，不应该包含label box信息，应该只是用于域标签的loss。

**Comment by farzeber** [comment]
![image](https://github.com/jinlong17/DA-Detect/assets/27004321/f1320c5e-bc55-4917-8f54-f8e73ca1fc49)

**Comment by farzeber** [comment]
![image](https://github.com/jinlong17/DA-Detect/assets/27004321/d7b9828f-5bfa-4e4d-83cc-c2c547c69bd0)

**Comment by farzeber** [comment]
![image](https://github.com/jinlong17/DA-Detect/assets/27004321/570c38ee-cffb-495f-be1a-ed0c6f1f8f99)

**Comment by jinlong17** [comment]
Hello, this is just loading, because I did not change the previous dataloader, but only used the source domain tag during training, and the remaining two were not used. you can review the DA-Detect/maskrcnn_benchmark/modeling/detector
/generalized_rcnn.py
